### PR TITLE
Add CI config for running tests and liniting

### PR DESCRIPTION
**Pull request by noandrea**
Tests are reported to Codecov
Linting is done via golangci-lint command 

closes: #68

### CODE REVIEW

**Comment by noandrea** [comment]
@SenorMonito please have a look especially at the CONTRIBUTING doc

**Review by PaddyMc — APPROVED** [review]
Awesome work, great PR :heart:

**Comment by SenorMonito** [comment]
> @SenorMonito please have a look especially at the CONTRIBUTING doc (cc @PaddyMc )

As per, Slack channel conversation, 

1. This version doesn't include enforcement guidelines as per the base [version](https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md). However we are agreed that this is more bureaucracy that is required right now. This can be addressed later
2. Need to confirm communication (email/discord or something else)

**Comment by noandrea** [comment]
The communication channel  has been decided to be an email, it has been added to the contribuiting file

There are a bunch of issues raised by the deepsource that we will take care little by little in the upcoming development

mergin now

**Pull request merged**
